### ISSUE TITLE
很眼熟的博客

### ISSUE THREAD

**Issue by pkwenda** [TyCoding/tumo#1]
这个系统好眼熟，参考了 [tale](https://github.com/otale/tale) 吗

**Comment by zoujiayu** [comment]
@ pkwenda
后台风格确认有点眼熟，改天看看代码层。

**Comment by TyCoding** [comment]
@pkwenda @zoujiayu 嗯呢，是参考了tale，前端因为都用的pinghsu主题，所以基本相同的。后台页面风格都是类似的，参考了很多开源项目设计风格，只不过使用的技术不同。
