### ISSUE TITLE
404 not found 

### ISSUE THREAD

**Issue by zjwmsg** [TyCoding/tumo#17]
GET http://localhost:8084/admin/js/api.js net::ERR_ABORTED 404

resource 文件下没有对应的js文件

**Comment by TyCoding** [comment]
> GET http://localhost:8084/admin/js/api.js net::ERR_ABORTED 404
> 
> resource 文件下没有对应的js文件

抱歉，我好像是提交的时候把这个文件误删了，最新的我已经提交上去了。
