### ISSUE TITLE
error: invalid path

### ISSUE THREAD

**Issue by wu2171613** [TyCoding/tumo#18]
git clone 时报这个错误
error: invalid path 'src/main/resources/static/admin/js/\.js'

操作系统：windows 10
终端：powershell
git version 2.23.0

**Comment by TyCoding** [comment]
> git clone 时报这个错误
> error: invalid path 'src/main/resources/static/admin/js/.js'
> 
> 操作系统：windows 10
> 终端：powershell
> git version 2.23.0

\.js 已经删除
